# Generated by Django 3.1.1 on 2020-10-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience_learnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='learnings',
        ),
        migrations.AddField(
            model_name='experience',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
